name: Code coverage
on: [push]

jobs:
    Coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Install coverage
              run: |
                  python -m pip install --upgrade pip
                  pip install coverage
            - name: Execute coverage
              run: coverage run --source=. -m pytest
            - name: Report
              run: coverage report
            - run: echo "Coverage executed"
              name: Echo