name: Code coverage
on:
    push:
        paths:
            - '**.py'
permissions:
    contents: write

jobs:
    Coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Install coverage
              run: |
                  python -m pip install --upgrade pip
                  pip install coverage coverage-badge
            - name: Execute coverage
              run: coverage run -m pytest
            - name: Report
              run: coverage report
            - name: Generate badge
              run: coverage-badge -o coverage.svg -f
            - name: Commit coverage badge
              run: |
                  git config --local user.email "coverage@ramayanquiz.com"
                  git config --local user.name "Ramayan Quiz Bot"
                  git add coverage.svg
                  git commit --allow-empty -m "Update coverage badge"
                  git push
            - run: echo "Coverage executed"
              name: Echo