name: Check programming and stylistic errors
on: [push]

jobs:
    Execute-Linters:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v5
              name: Setup Python
              with:
                python-version: '3.10'
            - run: echo "Linter executed"
              name: Echo